Master
Significant-Gravitas/Auto-GPT-Plugins pull request #139
Opened 2023-05-11 19:35 UTC by sdelgadoc

Fix encoding issues when reading emails using the email plugin.

2023-05-12 06:26 UTC, ntindle commented
Thanks! Can you add a matching test?

2023-05-12 06:26 UTC, ntindle requested changes
Add tests

2023-05-13 21:54 UTC, sdelgadoc commented
> Add tests

Added tests per request from @ntindle

2023-05-16 04:39 UTC, ntindle approved these changes

2023-05-16 04:39 UTC, merged