Create Astro plugin
Significant-Gravitas/Auto-GPT-Plugins pull request #46
Opened 2023-04-24 13:52 UTC by sr5434

Same as pull #1633 on Significant-Gravitas/Auto-GPT but as a plugin. It was approved by @nponeccop but I was asked to reimplement it as a plugin. I will include the old pull request message below.

### Background
The current agent cannot access real-time information about how many astronauts are in space.

### Changes

This uses the open notify api to get information about how many astronauts are in space.

### Documentation

I included a docstring for the function that fetches the data.

### Test Plan

I haven’t tested it, as I added my code on the main branch which is currently broken

### PR Quality Checklist
- [x] My pull request is atomic and focuses on a single change.
- [ ] I have thoroughly tested my changes with multiple different prompts.
- [x] I have considered potential risks and mitigations for my changes.
- [x] I have documented my changes clearly and comprehensively.
- [x] I have not snuck in any "extra" small tweaks changes 

I didn’t add tests because I forked master which is broken

2023-04-24 17:54 UTC, ntindle requested changes
Add tests and improve readme with some more context. Take a look at the email plug-in for examples

2023-04-24 17:54 UTC, ntindle commented
Really solid start!

2023-04-26 13:00 UTC, sr5434 commented
Is this better? Should I squash the commits?

2023-04-26 13:52 UTC, ntindle commented
This looks way better! I’ll be able to run/test it a bit later today. It’s 8am for me so by around 2am it should be reviewed

2023-04-26 14:32 UTC, sr5434 commented
Ok, thanks

2023-04-26 15:08 UTC, sr5434 commented on README.md
> +| YouTube   | Various YouTube features including downloading and understanding | [jpetzke/AutoGPT-YouTube](https://github.com/jpetzke/AutoGPT-YouTube)
Those are all 3rd party plugins. Mine is a first-party plugin.

2023-04-26 18:59 UTC, ntindle commented on README.md
> +| YouTube   | Various YouTube features including downloading and understanding | [jpetzke/AutoGPT-YouTube](https://github.com/jpetzke/AutoGPT-YouTube)
i can modify this if you're okay with it to add it

2023-04-26 19:21 UTC, sr5434 commented on README.md
> +| YouTube   | Various YouTube features including downloading and understanding | [jpetzke/AutoGPT-YouTube](https://github.com/jpetzke/AutoGPT-YouTube)
Oh I didn’t see it. I can add it. Should I squash the commits or leave them?

2023-04-27 06:26 UTC, ntindle requested changes
Only small test changes left!

2023-04-27 06:26 UTC, ntindle commented on src/autogpt_plugins/astro/test_astro_plugin.py
> +)
import from the correct module

2023-04-27 06:26 UTC, ntindle commented on src/autogpt_plugins/astro/test_astro_plugin.py
> +import unittest
Use pytest

2023-04-27 11:36 UTC, sr5434 commented on src/autogpt_plugins/astro/test_astro_plugin.py
> +)
Ok

2023-04-27 14:51 UTC, sr5434 commented
Is this better?

2023-04-28 15:59 UTC, sr5434 commented
@ntindle the tests pass when I ran them. Will this be merged?

2023-04-28 20:37 UTC, ntindle commented
Will get to this within the next 17 hours

2023-04-28 20:39 UTC, ntindle requested changes
Remove the merge conflict artifact or I can when I get time to run the tests

2023-04-28 20:39 UTC, ntindle commented on README.md
> +<<<<<<< HEAD
Merge artifact

2023-04-28 20:39 UTC, ntindle commented on README.md
> +# Auto-GPT-Plugin-Template
Merge artifact

2023-04-29 17:03 UTC, ntindle commented
I cannot for the life of me get it to execute the command. Try changing the name/description up or provide a prompt that I can use

2023-04-29 17:16 UTC, sr5434 commented
Ok, sure.

2023-04-29 17:19 UTC, sr5434 commented
I used the email plugin __init__.py as a template, and forgot to edit the description. It should(hopefully) work now.

2023-05-06 01:25 UTC, p-i- commented
This is a mass message from the AutoGPT core team to all open Plugin-PRs

We're in the process of re-architecting:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

Please be patient as we work to clean up the AutoGPT core.

If you already have an existing plug-in that’s affected, please message @ntindle on Discord so we can get your plugin spinning on the new 
architecture.

If you're working on a plugin, please bear in mind that one of our primary goals in re-architecting is to make life MUCH easier for you. 
We've taken aboard feedback from plugin developers. We're on it, so please give us some time!

<3 The AutoGPT Team

2023-05-10 02:28 UTC, merged