Bluesky integration
Significant-Gravitas/Auto-GPT-Plugins pull request #97
Opened 2023-05-02 15:48 UTC by hermanschutte

This plugin allows Auto-GPT to retrieve posts from Bluesky and create new posts. With Twitter becoming much stricter with developer apps, Bluesky is a good alternative.

2023-05-06 01:25 UTC, p-i- commented
This is a mass message from the AutoGPT core team to all open Plugin-PRs

We're in the process of re-architecting:
  https://github.com/Significant-Gravitas/Auto-GPT/wiki/Architecting

Please be patient as we work to clean up the AutoGPT core.

If you already have an existing plug-in that’s affected, please message @ntindle on Discord so we can get your plugin spinning on the new 
architecture.

If you're working on a plugin, please bear in mind that one of our primary goals in re-architecting is to make life MUCH easier for you. 
We've taken aboard feedback from plugin developers. We're on it, so please give us some time!

<3 The AutoGPT Team

2023-05-10 01:49 UTC, ntindle requested changes
Add atprototools to the requirements.txt

2023-05-10 01:51 UTC, ntindle requested changes
`SYSTEM:  Command post_to_bluesky returned: Error: 'Session' object has no attribute 'post_bloot'`

2023-05-10 01:57 UTC, ntindle commented
Consider https://github.com/marshalX/atproto over the library chosen as the library chosen breaks Python conventions.

2023-05-10 17:39 UTC, ntindle commented
It looks like one of your tests failed. Can you take a look?

2023-05-10 17:43 UTC, ntindle commented
![cce90813-dabf-4051-a70d-5ae2702954b4](https://github.com/Significant-Gravitas/Auto-GPT-Plugins/assets/8845353/b7396d7a-eee7-4661-b7ef-e5ff4cb82c25)
This is the image it generated to post btw

2023-05-12 04:23 UTC, ntindle commented
Would you take a look at the CI failure? 

https://github.com/Significant-Gravitas/Auto-GPT-Plugins/actions/runs/4936955336/jobs/8830687797?pr=97

2023-05-12 06:32 UTC, hermanschutte commented
> Would you take a look at the CI failure?
> 
> https://github.com/Significant-Gravitas/Auto-GPT-Plugins/actions/runs/4936955336/jobs/8830687797?pr=97

I'm getting this error when running the tests:

```
_ ERROR collecting src/autogpt_plugins/bluesky/bluesky_plugin/test_bluesky_plugin.py _
ImportError while importing test module '/home/runner/work/Auto-GPT-Plugins/Auto-GPT-Plugins/src/autogpt_plugins/bluesky/bluesky_plugin/test_bluesky_plugin.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/autogpt_plugins/bluesky/bluesky_plugin/test_bluesky_plugin.py:2: in <module>
    from .bluesky_plugin import (
E   ImportError: attempted relative import with no known parent package
```

Hi. No idea why it would be complaining about the module names? It matches the format of the other plugins as far as I can tell. Any ideas?

2023-05-12 07:20 UTC, ntindle requested changes

2023-05-12 07:20 UTC, ntindle commented on src/autogpt_plugins/bluesky/bluesky_plugin/test_bluesky_plugin.py
> +        self.assertIsInstance(get_latest_posts(MOCK_USERNAME, 5), str)
Can you swap to pytest?

2023-05-12 07:20 UTC, ntindle commented on src/autogpt_plugins/bluesky/bluesky_plugin/test_bluesky_plugin.py
> +        self.assertIsInstance(get_latest_posts(MOCK_USERNAME, 5), str)
jk thats for the other repo

2023-05-12 07:21 UTC, merged